### ISSUE TITLE
ids is not defined.

### ISSUE THREAD

**Issue by eduoliihezz** [codeuk/DiscordRAT#1]
Okay, I know that there is a new DiscordRAT (Trollware) that is updated and all that stuff. However, I want to improve this old project. All the code is clean and clear, without errors except a function named _"ids"_. This function is in three parts of the code.
```python
 if not uid or uid in ids:
                    continue
            ids.append(uid)
```
So the commands: _Tokenfuck, payments and token_ is not working for this error. I hope you can help me find a solution, also I will work in it.

**Comment by codeuk** [comment]
I haven't even looked at this project for months lol, but sure I'll look into it when I have time.
